App refactor
pandamaroder/OrderManagementSystem pull request #1
Opened 2024-09-12 19:31 UTC by pandamaroder

Init Commit :
Modules init commit 
1. Order-Service -> init commit for tests
2. Order-Status-Service
3. Common 

Separate gradle builds

2024-09-13 08:11 UTC, mfvanek commented
Для common модуля нужно указать версию Java в build.gradle.kts
```
java {
    sourceCompatibility = JavaVersion.VERSION_17
}
```

2024-09-13 08:14 UTC, mfvanek requested changes
Нужно убрать лишнюю конфигурацию для Кафки

2024-09-13 08:14 UTC, mfvanek commented on order-service/src/test/java/com/example/orderservice/support/KafkaInitializer.java
> +    private static final DockerImageName IMAGE_NAME = DockerImageName.parse("confluentinc/cp-kafka:7.5.3");
Используется не та версия Кафки. Должна быть такая. же, как и в compose файле

2024-09-13 08:14 UTC, mfvanek commented on order-service/src/test/java/com/example/orderservice/support/KafkaInitializer.java
> +            .withEnv("KAFKA_LISTENER_SECURITY_PROTOCOL_MAP", "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT");
Уберите строчку .`withEnv("KAFKA_LISTENER_SECURITY_PROTOCOL_MAP", "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT");`

2024-09-18 11:34 UTC, mfvanek requested changes
Нужно почистить проект от мусора: убрать закомментированный код и лишние зависимости

2024-09-18 11:34 UTC, mfvanek commented on order-service/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
В этом задании нет работы с БД. Лучше убрать

2024-09-18 11:34 UTC, mfvanek commented on order-service/src/main/java/com/example/orderservice/OrderListener.java
> +
Желательно почистить код от мусора

2024-09-18 11:34 UTC, mfvanek commented on order-service/src/main/java/com/example/orderservice/OrderListener.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(OrderListener.class);
Обычно это делаем через lombok

2024-09-18 11:34 UTC, mfvanek commented on order-service/src/main/java/com/example/orderservice/OrderServiceApplication.java
> +@ComponentScan(basePackages = {"com.example.orderservice", "com.example.common"})
Зачем это было добавлено?

2024-09-18 11:34 UTC, mfvanek commented on order-service/src/main/resources/application.yml
> +      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
Этот конфиг не будет нужен, если убрать лишние зависимости

2024-09-18 11:34 UTC, mfvanek commented on order-service/src/main/resources/application.yml
> +    order: order-topic
Дублирует `default-topic: order-topic`
Зачем?

2024-09-18 11:34 UTC, mfvanek commented on order-service/src/test/java/com/example/orderservice/support/TestBase.java
> +@AutoConfigureWebTestClient(timeout = "PT36S")
Это не нужно

2024-09-19 16:14 UTC, pandamaroder commented on order-service/src/test/java/com/example/orderservice/support/KafkaInitializer.java
> +    private static final DockerImageName IMAGE_NAME = DockerImageName.parse("confluentinc/cp-kafka:7.5.3");
resolved

2024-09-19 16:14 UTC, pandamaroder commented on order-service/src/test/java/com/example/orderservice/support/KafkaInitializer.java
> +            .withEnv("KAFKA_LISTENER_SECURITY_PROTOCOL_MAP", "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT");
resolved

2024-09-20 08:30 UTC, mfvanek requested changes
Не исправлены замечания

2024-09-20 08:30 UTC, mfvanek commented on order-service/src/main/java/com/example/orderservice/OrderController.java
> +    @Autowired
Над финальными полями не нужна аннотация `@Autowired`.
Здесь и в других местах

2024-09-20 08:30 UTC, mfvanek commented on order-service/src/test/java/com/example/orderservice/consumer/OrderStatusListenerTest.java
> +        consumerRecords = new LinkedBlockingQueue<>();
Зачем в этом тесте консьюмер?

2024-09-20 08:30 UTC, mfvanek commented on order-service/src/test/java/com/example/orderservice/controller/OrderControllerTest.java
> +    private final BlockingQueue<ConsumerRecord<String, String>> consumerRecords = new LinkedBlockingQueue<>();
Зачем здесь этот код?

2024-09-21 17:14 UTC, mfvanek approved these changes

2024-09-21 17:14 UTC, mfvanek commented on order-service/src/main/java/com/example/orderservice/OrderController.java
> +        kafkaTemplate.send(defaultTopic, order).get();
В API есть метод sendDefault, который отправляет в дефолтный топик

2024-09-21 17:14 UTC, mfvanek commented on order-service/src/test/java/com/example/orderservice/consumer/OrderStatusListenerTest.java
> +        kafkaTemplate.send(orderStatusTopic, orderStatusEvent);
Здесь нужно делать get(), чтобы заблокировать поток до отправки данных в Кафку

2024-09-23 07:07 UTC, pandamaroder commented on order-service/src/test/java/com/example/orderservice/consumer/OrderStatusListenerTest.java
> +        kafkaTemplate.send(orderStatusTopic, orderStatusEvent);
resolved

2024-09-23 07:09 UTC, pandamaroder commented on order-service/src/main/java/com/example/orderservice/OrderController.java
> +        kafkaTemplate.send(defaultTopic, order).get();
resolved

2024-09-25 07:50 UTC, merged